spring:
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/aop
    driver-class-name: org.h2.Driver
    username: sa

  data:
    jdbc:
      repositories:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  h2:
    console:
      enabled: true
      path: /h2-console

  mvc:
    path match:
      matching-strategy: ant_path_matcher

logging:
  level:
      hibernate:
        type:
          descriptor:
            sql: trace